### ISSUE TITLE
Support wired Bridge Types

### ISSUE THREAD

**Issue by fruggy83** [fruggy83/openocean#13]
Implement support for:
 * ~~TCP Bridges~~
 * FAM/FGW Bridges

**Comment by basty85** [comment]
Hey, thank you very much for your efforts, really like your bindings and the new possibility to use TCP Bridges. I got the Digital Concepts Smart EnOcean TCP/IP Gateway which uses login data to access the web interface, Simple- or REST API.
Would it be possible that you provide a username/password mockup to the tcpbridge binding since most IP Gateways with web interface can only be accessed via login data? Thank you in advance :-)

**Comment by fruggy83** [comment]
Hi Basty85 (@Basty85), 

I am afraid that I have to disappoint you. I read the docs of this device and did not found a wy to receive raw enocean data from it. They use a JSON like format which I do not support. This tcpbridge is intended for a ser2net setup.
However I found a [github project](https://github.com/Digital-Concepts/OpEnOcean) which could be interessting for you. They already developed a binding which can connect to your TCP/IP gateway.

Best regards
Daniel

**Comment by basty85** [comment]
Damn, never mind! Thanks for the link, I will definitely look that up.

**Comment by fruggy83** [comment]
Merged ESP2 branch into master and created a [PR ](https://github.com/openhab/openhab-addons/pull/6513)for official binding.
